#!/usr/bin/env python3
"""
GrokLLM Web Server (FastAPI)

The complete backend for the GrokLLM interactive demo.
Written entirely by Grok Build CLI — zero human-written code in this file.

Features:
- Loads the trained model once at startup
- /api/generate endpoint with full sampling controls
- Beautiful self-contained frontend
- Prominent autonomous-build attribution everywhere
"""

import os
import time
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

import torch

from grokllm.config import DEFAULT_CONFIG
from grokllm.generate import GrokGenerator
from grokllm.model import GrokLLM

# ------------------------------------------------------------------
# FastAPI App
# ------------------------------------------------------------------

app = FastAPI(
    title="GrokLLM API",
    description="A tiny real LLM + web UI built 100% autonomously by Grok Build CLI in YOLO mode",
    version="0.1.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# Global generator (loaded on startup)
generator: Optional[GrokGenerator] = None
MODEL_LOAD_TIME: Optional[float] = None
STARTUP_TIME = time.time()


class GenerateRequest(BaseModel):
    prompt: str = Field(default="To be or not to be", min_length=0, max_length=500)
    max_new_tokens: int = Field(default=180, ge=1, le=1024)
    temperature: float = Field(default=0.75, ge=0.01, le=2.0)
    top_k: Optional[int] = Field(default=40, ge=0, le=200)
    top_p: Optional[float] = Field(default=0.9, ge=0.0, le=1.0)
    seed: Optional[int] = Field(default=None, ge=0)


class GenerateResponse(BaseModel):
    text: str
    prompt: str
    generated_continuation: str
    tokens_generated: int
    elapsed_seconds: float
    tokens_per_second: float
    parameters: dict
    model_info: dict
    attribution: str = "This response was generated by a model trained and served by code written entirely by Grok Build CLI."


class HealthResponse(BaseModel):
    status: str
    model_loaded: bool
    uptime_seconds: float
    device: Optional[str] = None
    parameters: Optional[int] = None
    checkpoint: Optional[str] = None
    attribution: str


# ------------------------------------------------------------------
# Startup / Model Loading
# ------------------------------------------------------------------

def load_model_if_available() -> Optional[GrokGenerator]:
    """Try to load the default checkpoint. Return None if not present."""
    ckpt_path = os.path.join(DEFAULT_CONFIG.checkpoint_dir, DEFAULT_CONFIG.checkpoint_name)

    if not os.path.exists(ckpt_path):
        print(f"[GrokLLM] No checkpoint found at {ckpt_path}")
        print("[GrokLLM] Train one with: python train.py")
        return None

    print(f"[GrokLLM] Loading checkpoint from {ckpt_path} ...")
    t0 = time.time()
    gen = GrokGenerator.from_checkpoint(ckpt_path)
    dt = time.time() - t0
    print(f"[GrokLLM] Model loaded in {dt:.2f}s on {gen.device} "
          f"({sum(p.numel() for p in gen.model.parameters()):,} params)")
    return gen


@app.on_event("startup")
async def startup_event():
    global generator, MODEL_LOAD_TIME
    generator = load_model_if_available()
    MODEL_LOAD_TIME = time.time()


# ------------------------------------------------------------------
# Routes
# ------------------------------------------------------------------

@app.get("/", response_class=HTMLResponse)
async def serve_frontend():
    """Serve the beautiful single-file frontend."""
    # The frontend lives in web/index.html
    frontend_path = os.path.join(os.path.dirname(__file__), "web", "index.html")

    if os.path.exists(frontend_path):
        with open(frontend_path, "r", encoding="utf-8") as f:
            html = f.read()
        return HTMLResponse(content=html)

    # Fallback: very basic page if frontend file missing (should never happen)
    return HTMLResponse(content="""
    <html><body style="font-family: system-ui; padding: 2rem;">
    <h1>GrokLLM</h1>
    <p>Frontend file missing. Run from project root.</p>
    <p>This entire project was built autonomously by Grok Build CLI.</p>
    </body></html>
    """)


@app.get("/api/health", response_model=HealthResponse)
async def health():
    """Health + model status endpoint."""
    global generator

    ckpt = os.path.join(DEFAULT_CONFIG.checkpoint_dir, DEFAULT_CONFIG.checkpoint_name)
    uptime = time.time() - STARTUP_TIME

    if generator is None:
        return HealthResponse(
            status="no_model",
            model_loaded=False,
            uptime_seconds=round(uptime, 1),
            attribution="GrokLLM was built 100% by Grok Build CLI. Run `python train.py` to create a model.",
        )

    return HealthResponse(
        status="ok",
        model_loaded=True,
        uptime_seconds=round(uptime, 1),
        device=str(generator.device),
        parameters=sum(p.numel() for p in generator.model.parameters()),
        checkpoint=ckpt,
        attribution="This server and model were created entirely by the Grok Build CLI in one autonomous session.",
    )


@app.post("/api/generate", response_model=GenerateResponse)
async def generate(req: GenerateRequest):
    """Main text generation endpoint."""
    global generator

    if generator is None:
        raise HTTPException(
            status_code=503,
            detail="No trained model loaded. Run `python train.py` first, then restart the server."
        )

    try:
        result = generator.generate(
            prompt=req.prompt,
            max_new_tokens=req.max_new_tokens,
            temperature=req.temperature,
            top_k=req.top_k if req.top_k and req.top_k > 0 else None,
            top_p=req.top_p if req.top_p and req.top_p < 1.0 else None,
            seed=req.seed,
        )

        return GenerateResponse(
            text=result["text"],
            prompt=result["prompt"],
            generated_continuation=result["generated_continuation"],
            tokens_generated=result["tokens_generated"],
            elapsed_seconds=result["elapsed_seconds"],
            tokens_per_second=result["tokens_per_second"],
            parameters=result["parameters"],
            model_info=result["model_info"],
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Generation failed: {str(e)}")


@app.get("/api/model-info")
async def model_info():
    """Return basic model metadata."""
    global generator

    if generator is None:
        return {"loaded": False, "message": "Train a model first with `python train.py`"}

    cfg = generator.model.config
    return {
        "loaded": True,
        "parameters": sum(p.numel() for p in generator.model.parameters()),
        "config": {
            "n_layer": cfg.n_layer,
            "n_head": cfg.n_head,
            "n_embd": cfg.n_embd,
            "block_size": cfg.block_size,
            "vocab_size": cfg.vocab_size,
        },
        "device": str(generator.device),
        "attribution": "Model architecture and weights produced by code written 100% by Grok Build CLI.",
    }


@app.get("/api/attribution")
async def attribution():
    """Explicit attribution endpoint (for fun and transparency)."""
    return {
        "project": "GrokLLM",
        "built_by": "Grok Build CLI (Grok 4.3 by xAI)",
        "build_mode": "YOLO / always-approve",
        "human_code_edits": 0,
        "human_steering": "one-word commands only (e.g. 'fix')",
        "date": "April 2026",
        "message": "This entire API, the model, the training code, and this response were written autonomously.",
    }


# Optional: mount static if someone adds assets later
if os.path.isdir("web/static"):
    app.mount("/static", StaticFiles(directory="web/static"), name="static")


def main():
    """Run the server directly (for `python app.py` or `grokllm-serve`)."""
    import uvicorn

    print("=" * 72)
    print("  GrokLLM Web Server")
    print("  Built 100% autonomously by Grok Build CLI in YOLO mode")
    print("  No human wrote any of this code.")
    print("=" * 72)

    port = int(os.environ.get("PORT", 8000))
    uvicorn.run("app:app", host="0.0.0.0", port=port, reload=False)


if __name__ == "__main__":
    main()
